export const mockUsers = [
	{
		id: "u1",
		name: "Alice Johnson",
		email: "alice@corp.io",
		role: "Admin",
		orders: 14,
	},
	{
		id: "u2",
		name: "Bob Martinez",
		email: "bob@corp.io",
		role: "Customer",
		orders: 7,
	},
	{
		id: "u3",
		name: "Carol White",
		email: "carol@acme.com",
		role: "Customer",
		orders: 3,
	},
	{
		id: "u4",
		name: "David Lee",
		email: "david@bigco.com",
		role: "Customer",
		orders: 21,
	},
	{
		id: "u5",
		name: "Eva Chen",
		email: "eva@startup.io",
		role: "Admin",
		orders: 2,
	},
	{
		id: "u6",
		name: "Frank Torres",
		email: "frank@corp.io",
		role: "Customer",
		orders: 9,
	},
	{
		id: "u7",
		name: "Grace Kim",
		email: "grace@acme.com",
		role: "Customer",
		orders: 5,
	},
	{
		id: "u8",
		name: "Henry Brown",
		email: "henry@bigco.com",
		role: "Customer",
		orders: 18,
	},
	{
		id: "u9",
		name: "Iris Patel",
		email: "iris@startup.io",
		role: "Customer",
		orders: 11,
	},
	{
		id: "u10",
		name: "James Wilson",
		email: "james@corp.io",
		role: "Customer",
		orders: 6,
	},
];

export const mockProducts = [
	{
		id: "p1",
		name: "Custom Box S",
		sku: "BOX-S-001",
		price: "$4.99",
		status: "Active",
	},
	{
		id: "p2",
		name: "Custom Box M",
		sku: "BOX-M-001",
		price: "$7.49",
		status: "Active",
	},
	{
		id: "p3",
		name: "Custom Box L",
		sku: "BOX-L-001",
		price: "$11.99",
		status: "Active",
	},
	{
		id: "p4",
		name: "Mailer Envelope",
		sku: "MAIL-ENV-01",
		price: "$2.99",
		status: "Active",
	},
	{
		id: "p5",
		name: "Tissue Paper Pack",
		sku: "TIS-PPR-01",
		price: "$8.99",
		status: "Inactive",
	},
	{
		id: "p6",
		name: "Branded Tape Roll",
		sku: "TAPE-001",
		price: "$3.49",
		status: "Active",
	},
];

export const mockEntitlements = [
	{
		id: "e1",
		user: "bob@corp.io",
		product: "Custom Box M",
		grantedBy: "alice@corp.io",
		grantedAt: "2026-02-14",
	},
	{
		id: "e2",
		user: "carol@acme.com",
		product: "Custom Box S",
		grantedBy: "alice@corp.io",
		grantedAt: "2026-02-15",
	},
	{
		id: "e3",
		user: "david@bigco.com",
		product: "Mailer Envelope",
		grantedBy: "eva@startup.io",
		grantedAt: "2026-02-20",
	},
	{
		id: "e4",
		user: "frank@corp.io",
		product: "Custom Box L",
		grantedBy: "alice@corp.io",
		grantedAt: "2026-02-22",
	},
	{
		id: "e5",
		user: "grace@acme.com",
		product: "Branded Tape Roll",
		grantedBy: "eva@startup.io",
		grantedAt: "2026-02-28",
	},
	{
		id: "e6",
		user: "henry@bigco.com",
		product: "Custom Box M",
		grantedBy: "alice@corp.io",
		grantedAt: "2026-03-01",
	},
	{
		id: "e7",
		user: "iris@startup.io",
		product: "Tissue Paper Pack",
		grantedBy: "eva@startup.io",
		grantedAt: "2026-03-03",
	},
	{
		id: "e8",
		user: "james@corp.io",
		product: "Custom Box S",
		grantedBy: "alice@corp.io",
		grantedAt: "2026-03-06",
	},
];

export const mockActivityItems = [
	{
		id: "a1",
		initials: "JD",
		action: "JD granted Product A to bob@corp.io",
		timestamp: "2 min ago",
		color: "bg-orange-500",
	},
	{
		id: "a2",
		initials: "AL",
		action: "alice@corp.io created a new user carol@acme.com",
		timestamp: "18 min ago",
		color: "bg-blue-500",
	},
	{
		id: "a3",
		initials: "DB",
		action: "david@bigco.com placed order #8821",
		timestamp: "1 hr ago",
		color: "bg-green-500",
	},
	{
		id: "a4",
		initials: "EP",
		action: "eva@startup.io updated product Custom Box L",
		timestamp: "3 hrs ago",
		color: "bg-purple-500",
	},
	{
		id: "a5",
		initials: "FT",
		action: "frank@corp.io's entitlement for Mailer Envelope was revoked",
		timestamp: "5 hrs ago",
		color: "bg-slate-400",
	},
	{
		id: "a6",
		initials: "GK",
		action: "grace@acme.com placed order #8820",
		timestamp: "Yesterday",
		color: "bg-teal-500",
	},
];
