import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "NextGen Packaging",
	description: "Generated by NextGen Packaging",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en" className="scroll-smooth">
			<body className="antialiased">
				{children}
				<Toaster position="bottom-right" />
			</body>
		</html>
	);
};

export default RootLayout;
