import type { Metadata } from "next";
import "./globals.css";

// TODO: Add fonts here.

export const metadata: Metadata = {
  title: "NextGen Packaging",
  description: "Generated by NextGen Packaging",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
